borgbase/vorta

src/vorta/__main__.py, vorta.spec
- cwd must be the repo dir, `__FILE__` is not available here
- the borg binary for the platform must be in bin/borg (no matter
whether we build for Linux or macOS or ...)
- moved some settings to top of the file
- whitespace clean up
fixes #76.
=> pyinstaller / vorta.spec: make platform independent

src/vorta/__main__.py
this avoids that someone e.g. porting to freebsd (which is also
supported by PyInstaller) will stumble over the platform check.
likely this is a very general problem with the fat binaries:
i suspect it is due to the pyinstaller bootloader / wrapper
cleaning up the temporary directory _MEIxxxxx where it extracted
all the needed files after the main process terminates (sys.exit()),
being unaware that we have just generated a background process also
relying on these files.
for the linux case, this led to some strange exception from pytz
that the current timezone is not supported (likely because it failed
to load some pytz tz definition file which was already gone).
=> do not fork into background with any fat binary

README.md, requirements.d/conda.yml, src/vorta/models.py, src/vorta/views/misc_tab.py
And don't show settings that exist in the DB, but not in `vorta.models`.
=> Remove leftover Sentry references. Fixes #127

src/vorta/utils.py
I store my ControlMaster sockets in `~/.ssh/` due to `ControlPath ~/.ssh/%r@%h:%p` in my ssh config. While trying to read private key files, Vorta stumbled upon these sockets and crashed on startup:
```
File "/Users/seb/.pyenv/versions/3.6.8/lib/python3.6/site-packages/paramiko/pkey.py", line 278, in _read_private_key_file
with open(filename, "r") as f:
OSError: [Errno 102] Operation not supported on socket: '/Users/seb/.ssh/seb@asdf'
```
=> get_private_keys: do not try to read sockets

src/vorta/models.py, src/vorta/utils.py
When I first ran Vorta, I didn't see the macOS menu bar icon at all because I'm using dark mode. So I thought the app doesn't work. Until I realized that I have to configure the app explicitly to use a light icon. Could be confusing for end users.
This code sets `use_light_icon=True` if macOS dark mode is detected on the first run of the app.
=> Programmatically detect theme color (for macOS)

src/vorta/views/archive_tab.py
Showing the last 5 characters of the mount points doesn't give much
information, so we now allow the user to resize the mount_point column
and allow Qt to draw an ellipsis and the number of characters that
fit in the column (or the whole mount point if it fits).
=> Use ellipsis the Qt way in the archive table

src/vorta/utils.py
In `vorta.utils.get_mount_points` the call to `process.name()` may raise an exception (e.g. zombie processes on macOS). In that case, Vorta will crash. This PR fixes this by catching exceptions in `process.name()`: if we can't get the process name, this is obviously not an active borg mount.
=> Fix crash due to zombie processes

CONTRIBUTING.md, src/vorta/i18n/__init__.py, src/vorta/log.py
check how the UI behaves for longer / shorter strings, for RTL strings.
does currently only work IF a language is loaded from a .qm file, otherwise there won't be a translator object / it won't call its .translate method.
works:
```
LANG=de_DE TRANS_SCALE=200 vorta --foreground
```
=> implement TRANS_SCALE env var for i18n UI layout checking

src/vorta/views/archive_tab.py
The delete button might be dangerous for some users who might click it accidentally. Now the user is asked for confirmation before performing a destructive irreversible action.
Also, some fixes: remove unused code, translate a missing text which wasn't translated and remove a duplicated line (which was setting an untranslated status text just after the translated text was set).
=> Ask for confirmation on delete (and small fixes)

CONTRIBUTING.md
The contribution doc wasn't updated to include info about the different dark and light icon sets. This commit address the documentation issue.
=> Update contribution info regarding icon imports

src/vorta/assets/UI/mainwindow.ui
**Background:**
Currently the "rename" and "delete" profile buttons have mouse-over
tooltips. This commit adds a tooltip to the "add profile" button
**Modifications:**
* Change the string property on `profileAddButton` from `text` to `toolTip`.
**Steps to test:**
* Launch Vorta and mouse-over the "+" button.
Fixes https://github.com/borgbase/vorta/issues/183
=> Add tooltip to "add profile" button (#183)

src/vorta/views/archive_tab.py, src/vorta/views/repo_add_dialog.py
We don't translate those logging messages, so no need to mark them.
Individual messages can still be translated where they're produced. Eg.
`self.app.backup_log_event.emit(self.tr('Starting consistency check...'))`
=> Remove translation functions for Borg logging messages. Fixes #197

src/vorta/borg/borg_thread.py, src/vorta/utils.py
This (hopefully) avoids the deadlock situation mentioned in the [Python docs](https://docs.python.org/3.6/library/subprocess.html) and [this SO question](https://stackoverflow.com/questions/42257512/difference-between-subprocess-popen-preexec-fn-and-start-new-session-in-python):
> The preexec_fn parameter is not safe to use in the presence of threads in your application. The child process could deadlock before exec is called. If you must use it, keep it trivial! Minimize the number of libraries you call into.
In addition it avoids getting the details of terminated Borg processes when looking for mount points. Discussed [here](https://github.com/giampaolo/psutil/issues/783).
=> Avoid deadlock when calling subprocess.Popen()

src/vorta/borg/borg_thread.py
We experienced some problems on MacOS 10.11.6, Borg 1.1.9 (installed with brew cask) where borg could not find the ssh key when there was a tilde in the path to the key file. Setting the `BORG_RSH` environment variable to expanded paths works. This patch fixes this for Vorta, we tested it on said setup.
=> Expand user path in python before setting BORG_RSH

src/vorta/models.py
=> Changes vorta's default tray icon to white on GNOME

src/vorta/views/archive_tab.py
I didn't realize that #156 by @antlarr removed the option to mount a whole repo. I think this is useful functionality and I had someone ask for it today. So I have re-enabled it in this PR.
The UI could be improved a bit. Currently it works by pressing the "Mount" button, while no archive is selected. And it's not possible to unmount the whole from the UI. The latter could be added. I'm just not sure on how to deselect all archives in a sensible way.
=> Allow mounting a whole repo again.

.github/ISSUE_TEMPLATE/bug_report.md, .gitignore, src/vorta/application.py, src/vorta/assets/UI/misctab.ui, src/vorta/borg/borg_thread.py, src/vorta/borg/version.py, src/vorta/views/main_window.py, src/vorta/views/misc_tab.py, tests/conftest.py
Adds a new borg command `version` to get the path and version of the Borg binary in use. This command is run once when the application is created and then displayed in the Misc tab.
This should be useful for debugging and possibly later to account for breaking changes in Borg itself.
Last, there is now a link to the log-folder in the Misc-tab to make it easier to find.
Fixes #205, #230, #120 and possibly #121 .
=> Get borg version and path on startup. Link to log folder.

setup.cfg, src/vorta/application.py, src/vorta/borg/_compatibility.py, src/vorta/borg/create.py, src/vorta/utils.py, src/vorta/views/main_window.py, src/vorta/views/misc_tab.py, src/vorta/views/repo_add_dialog.py, src/vorta/views/repo_tab.py
=> Add helper class to manage Borg version and supported features.

vorta.spec
Seems like Pyinstaller doesn't look at the system encoding and falls back to `C`. I noticed this with QLocale as well. Translations still work, but the `locale.getpreferredencoding(False)` falls back to ASCII, when we need UTF-8. There is a workaround to set an env var in the bundle.
Let's see if this error also occurs with Linux binaries.
See also https://github.com/pyinstaller/pyinstaller/issues/3592#issuecomment-400229431
I'm not using the `LANG` parameter to use the correct translations. Would appreciate some testing on macOS.
Test DMG: https://files.qmax.us/vorta-0.6.16.dmg
=> Correctly set environment encoding (pyinstaller+macOS). Fixes #220

src/vorta/views/source_tab.py
There's a minor bug in the the sources panel.
Clicking 'Remove' when no folders/files are selected causes vorta to crash because item is `None`
=> Don't delete item from sources if item==None

src/vorta/utils.py
.ssh can contain ControlPath sockets when trying to read SSH a key files.
Fixes Github borgbase/vorta issue #268
=> Handle OSError 6 when trying to read a socket

src/vorta/utils.py
See #273
Tested by running a Python process as root. `$ sudo python`
=> Ignore Python processes owned by other users when finding mount point

src/vorta/borg/borg_thread.py
I wonder if there should be a mention of this in the UI somewhere.
=> If BORG_PASSCOMMAND is found, unset BORG_PASSPHRASE. Fixes #272

README.md
I would like to propose to add a Vorta-specific chat rooms.
Benefits should be clear: Discussing stuff which does not belong in a chat room, support, attract beta testers,...
Why Matrix?
It seems like the most popular chat protocol for open source projects is IRC, but it is not beginner-friendly and you have to be online to receive messages.
Matrix is as easy to use as modern messengers (similar to Slack), supports all operating systems (including iOS and Android), it offers a web client and if there are too many people who miss IRC: Matrix also offers an IRC Bridge. 
I already created a room for this purpose.
I noticed that especially GNOME projects are moving to Matrix (https://wiki.gnome.org/Initiatives/Matrix), I am not sure about other projects.
=> Adding Matrix

src/vorta/views/diff_result.py
I encountered an exception being thrown when viewing diff of two archives.
The exception was
'''
vorta/views/diff_result.py", line 52, in parse_line
size = int(size)
ValueError: invalid literal for int() with base 10: ''
'''
which was caused by diff line:
'''
0 B   -2.6 kB home/philroche/.config/google-chrome/Profile 1/QuotaManager-journal
'''
This commit fixes the issue by only stripping +/- from string if they exist.
=> Bugfix for handling 0 byte modification in diff view

src/vorta/views/archive_tab.py
This enables column sorting for the table on the archive list page.
However, all columns are sorted by lexical string order. For example,
this means that archives with "52 MB" are ranked greater than "332 MB".
I wasn't able to figure out how to implement custom sorting behaviors. I did a fair amount of research and it doesn't look like PyQt supports this feature.
Completes: https://github.com/borgbase/vorta/issues/349
=> Enable sorting of archive table columns (#349)

src/vorta/views/diff_result.py
There could exist a scenario when a +/- would be not at the start of the string.
Current code would fail in this case.
Instead we should check that the first character of the string is +/-.
This following on from PR # 356 https://github.com/borgbase/vorta/pull/356
=> Improve checks for +/- in diff line

src/vorta/views/main_window.py
I actually wanted to package this with some error handling, but I now realise that this does not make sense without implementing error handling in general (see https://github.com/borgbase/vorta/issues/374).
Therefore this PR only removes the refresh after a profile change, which I found quite convenient but caused problems for @m3nu.
=> Don't refresh after profile change anymore

src/vorta/__main__.py, src/vorta/application.py, src/vorta/log.py, src/vorta/models.py, src/vorta/utils.py
This changes the default startup behavior from forking to the background to always start in foreground unless the existing argument `--daemonize` is used. Reasons for this change:
- Forking a Python process is broken on macOS. (see [1](https://bugs.python.org/issue33725) and [2](https://docs.python.org/3/library/multiprocessing.html#multiprocessing-start-methods)). There are rendering issues, random hangs or file access errors (seen with sqlite).
- Most uses seem to need it running in foreground: starting from Flatpak, starting from a macOS bundle, debugging.
- It removes some overly complicated startup conditions.
- There was always some confusion when users didn't see the system tray icon after starting it the first time.
Summary of changes:
- remove `--foreground` argument
- always run …
=> Run in foreground by default

src/vorta/assets/icons/scalable/com.borgbase.Vorta.svg
I tried to update the Vorta on flathub today, but noticed that with v0.6.24 the icon is stretched.
Please don't ask me why it worked until now, but by adding making the icon rectangular everything works again.
Because of that I will wait until v0.6.25 is released, before I update Vorta on flathub.
=> Make Vorta icon rectangular

src/vorta/assets/metadata/com.borgbase.Vorta.appdata.xml
The first tab of the app contains:
> For simple and secure backup hosting, try [BorgBase]
which links to https://borgbase.com/, which advertises hosting for Borg
repositories, starting at $2/month. This nudge towards spending real
money should be reflected in the OARS data.
The “mild” level of money-purchasing is defined as:
> Mild: Users are encouraged to donate real money, e.g. using Patreon
The “intense” level is:
> Intense: Ability to spend real money in-app, e.g. buying new content or new levels
The spending of money is not in-app here, but there is some mild
encouragement.
=> appdata: Add money-purchasing to OARS data

src/vorta/utils.py
Fixes https://github.com/borgbase/vorta/issues/416
It just displays NaN now, instead of crashing the application completely:
=> Display "NaN" if size of borgrepository is out of bounds

tests/test_archives.py
This fixes most of the errors. Still getting a rarer "abort" error on macOS only. Fixes #464
=> Avoid starting Borg thread at the end of test.

setup.cfg, src/vorta/application.py, src/vorta/assets/UI/sourcetab.ui, src/vorta/models.py, tests/test_source.py
- Display a proper error message when there is an issue with the Borg binary (wrong return code, not found, ..) #333 
- Fix PyQt to versions below 5.15 for now
- Small change to file exclusion placeholder text. #314
=> Add error message when Borg binary is missing. Fixes #333

src/vorta/application.py, src/vorta/assets/UI/sourcetab.ui, src/vorta/scheduler.py
(and change example in source tab to be cross-platform: **/.cache and .nobackup)
=> Notify of errors after system tray backup run. Fixes #105

src/vorta/views/main_window.py, src/vorta/views/profile_add_edit_dialog.py
My original fix for the bug is just the first commit, but I found another bug while fixing it.
The warnings for zero length or same profile name do not show up, as the save button seems to immediately close the window. My fix was to disable the save button when the profile name is invalid.
fixes #512
=> Prevent profiles from sharing the same name

src/vorta/views/diff_result.py, tests/test_archives.py
Fixes #521. I hope this is the last one, I haven't found any other formats in the Borg's code.
=> Parse owner changes in borg diff results

.github/workflows/main.yml
Currently workflows can run for 6 hours before automatically being stopped. 
There is a limit of 5 macOS jobs at a time, while each action runs 3 macOS jobs, meaning that 2 mistakes can block macOS jobs for 6 hours. (I'm surprised no one else has done a similar thing before)
~~This wastes 360 minutes of run time while there are only 2000 minutes per month of time (I assume this is using the free plan).~~
For example, I accidentally pushed 3 infinite loops:
https://github.com/borgbase/vorta/actions/runs/174077306
https://github.com/borgbase/vorta/actions/runs/174058136
https://github.com/borgbase/vorta/actions/runs/174054779
~~Since the timeout is so high, I will end up wasting 1080 minutes of run time, while with this change I would have wasted only 30.~~
10 minutes is a decent …
=> CI Fix-Set 10 minute test job time

src/vorta/autostart.py, tests/test_misc.py
Changed it so it reads the desktop file in src/assets/metadata instead of hardcoding it. It also uses XDG_CONFIG_HOME for non-flatpak installs (Can't do in flatpak since it gets overridden). 
Also added a test, it might break in the future since clicking qcheckboxes is weird.
=> Refactor Linux autostart

src/vorta/i18n/__init__.py
Sometimes we use the LANG env var to set the UI language. Previously QLocale would auto-detect the language when receiving None (LANG var not set). This doesn't work any more. So do a check if LANG is set and then let Qt detect it.
Reported by user Moritz M.
=> Cant pass None to QLocale any more. Will result in loading "C" locale.

CONTRIBUTORS.md
With @samuel-w very active recently, I suggest to formalize his project contributions by adding him as maintainer with equivalent permissions. While his PRs have often benefitted from constructive feedback, he is also very receptive to the same, which I find more important than providing a perfect PR from the start. So everyone, please continue offering guidance to him.
Furthermore, I suggest adding @ThomasWaldmann as second project admin in the interest of redundancy, should I get hit by a bus.😵
=> Add @samuel-w as contributor and maintainer

.gitignore, .tx/config, MANIFEST.in, Makefile, tests/conftest.py
When using English with a non-US region, our `en-US` default language file wasn't loaded.
This change renames the source language to just `en`.
See also https://doc.qt.io/qt-5/qtranslator.html#load-1
=> Use naked en locale rather than en_US. Fixes #623

src/vorta/network_status/darwin.py
Fix a bug where it tried to convert a datetime object to datetime again, when it should be a string.
=> Avoid formatting date and time twice. Fixes #624

src/vorta/borg/create.py, src/vorta/utils.py, src/vorta/views/main_window.py
This avoids problems with `vorta -d` and fork. The problems were mentioned here: https://github.com/borgbase/vorta/issues/629#issuecomment-688998973
=> Initialize the network status monitor lazily

tests/conftest.py, tests/test_archives.py
Cancel and confirm BorgThread is stopped at the end of each test to avoid false positive test errors.
Fixes #632
=> Cancel Borg thread at end of test.

.github/stale.yml, src/vorta/views/utils.py
Turns out, Vorta uses over 300 MB of RAM. The reason is super dumb.
The reason is the icons are imported as 1792 by 1792 images. Each one takes 14MB of memory. No one needs that. 128x128 uses no memory at all.
Now its about 163 MB RAM. Much better.
Before:
```
Line #    Mem usage    Increment   Line Contents
================================================
83    144.2 MiB    144.2 MiB       @profile
84                                 def set_icons(self):
85    158.7 MiB     14.5 MiB           self.extractButton.setIcon(get_colored_icon('cloud-download'))
86    172.6 MiB     13.9 MiB           self.mountButton.setIcon(get_colored_icon('folder-open'))
87    184.7 MiB     12.1 MiB           self.checkButton.setIcon(get_colored_icon('check-circle'))
88    197.1 MiB     12.4 MiB …
```
=> Reduce icon memory usage

.github/ISSUE_TEMPLATE/bug_report.md
We don't seem to have many bugs due to Borg errors, but we do have many due to packaging issues.
This helps diagnosing issues without having to ask more questions.
=> Replace Borg version with install method

.github/stale.yml, src/vorta/views/utils.py
Some icons are imported as lower resolution, so dividing by a constant will result in slight blurriness.
The only icon that is affected by this the diff icon, but other icons in the future might have this behaviour.
Still has the memory saving property.
=> Set all icons to same height

src/vorta/application.py
Used to be "vorta". Now its "Vorta" in the tray. 
I had an idea to basically mirror the tray status text, but it would have to hook into too many things and would be a pain to maintain.
=> Set application name

src/vorta/views/main_window.py
Fixes case where main window gets larger every time Vorta is opened.
=> Save window size correctly

src/vorta/borg/borg_thread.py, src/vorta/borg/info.py, src/vorta/borg/init.py
This limits accepting unknown SSH host keys to the inital repo setup. I.e. `borg info` and `borg init`. All other operations would fail if the original host key changed.
This is a trade-off between usability and security. Eventually we'd like to ask for the host key fingerprint when adding a new repo and verify it when adding.
See also: #714
=> Re-enable SSH host key checking for all operations except when adding repo

.coveragerc, .github/workflows/main.yml
Now that we have a Debian package, it would be nice to track our code test case coverage
Example:
https://codecov.io/gh/samuel-w/vorta-1/tree/6eef88395b9b3aa5e5514957c95f7efb77af4c54
=> CI: Integrate codecov.io

src/vorta/views/main_window.py, src/vorta/views/profile_add_edit_dialog.py, tests/conftest.py, tests/test_profile.py
exec_ not recommended per documentation https://doc.qt.io/qt-5/qdialog.html#exec.
Now the tests run on the actual client
rootdir is copied from #548
=> Refactor add and rename to not use exec_

src/vorta/__main__.py, src/vorta/application.py, src/vorta/views/archive_tab.py, src/vorta/views/extract_dialog.py, src/vorta/views/main_window.py, src/vorta/views/repo_add_dialog.py, src/vorta/views/repo_tab.py, tests/borg_json_output/delete_stderr.json, tests/test_archives.py, tests/test_profile.py, tests/test_repo.py
That should be the last of the dialog exec_.
I'm doing this to prepare for PyQt6 https://riverbankcomputing.com/software/pyqt/download.
=> Remove last exec_ instances, add archive deletion test, retain archive deletion message

src/vorta/utils.py, src/vorta/views/partials/tree_view.py
Fixes #646, fixes #664.
Sorts both diff and restore due to inheritance. Puts folders first then files, but doesn't allow changing of sorting order.
=> Sort tree dialogs alphabetically

src/vorta/assets/UI/repotab.ui
This makes the labels slightly off center, but its clear enough which labels go where and most Qt themes seem to automatically align the text anyways. Fixes #756
=> Fix label colour not changing on dark mode change

src/vorta/utils.py
Used setOption. Fixes #693.
I have no idea why this fixes it but it fixes it. The two dialogs look different but it doesn't matter at this point.
=> Fix file selector dialog

src/vorta/keyring/abc.py
=> Change keyring priority

src/vorta/utils.py
=> Catch more possible SSH key parsing errors.

.github/workflows/test.yml, requirements.d/dev.txt, src/vorta/network_status/abc.py, src/vorta/network_status/darwin.py, src/vorta/network_status/network_manager.py, src/vorta/utils.py
Take known Wifis from other profiles, rather than system.
Fixes #766
=> Remove support for deprecated macOS XML wifi list.

.github/workflows/test.yml, src/vorta/application.py, src/vorta/utils.py, tests/conftest.py, tests/test_source.py, tests/test_utils.py
=> Test fixes, avoid segfault at end

src/vorta/borg/info_archive.py, src/vorta/borg/info_repo.py, src/vorta/borg/refresh_archive.py, src/vorta/views/archive_tab.py, src/vorta/views/repo_add_dialog.py
allow individual archives to do a more complete refresh, pulling in/updating size and duration. (see discussion #828)
=> add option to refresh individual archives

src/vorta/borg/borg_thread.py
=> Remove failing SSH key check

src/vorta/keyring/kwallet.py
Fixes #897. To test with Pip:
`pip install --force-reinstall git+https://github.com/m3nu/vorta.git@issue/897/kdewallet-handle`
=> Fix issue with unassigned self.handle

.github/workflows/test.yml, src/vorta/application.py, src/vorta/borg/borg_thread.py, src/vorta/keyring/abc.py, src/vorta/keyring/darwin.py, src/vorta/keyring/db.py, src/vorta/keyring/kwallet.py, src/vorta/keyring/secretstorage.py, src/vorta/models.py, src/vorta/utils.py, src/vorta/views/repo_add_dialog.py, tests/conftest.py
This PR tries to avoid common issues with system keychains that were reported:
- Add option to avoid using system keychain.
- Prioritize keychains first. Then try to start them.
- Maintenance: Possible fixes for hung tests and segfault on exit on some setups.
To test:
`$ pip install --force-reinstall git+https://github.com/m3nu/vorta.git@issue/make-keyring-optional`
In *Misc* tab disable the setting "Store repository passwords in system keychain...". After that all repo passwords will be stored with Vorta only, independent of the system keychain.
=> Allows to fully disable using the system keychain.

src/vorta/borg/list_archive.py, src/vorta/views/archive_tab.py, src/vorta/views/extract_dialog.py, tests/borg_json_output/list_archive_stdout.json
This change relies on using borg >= 1.1.0. Do we need to support older versions? If so, I can add checks for borg version and fallback to old text parsing. This fixes one of the 2 cases in issue #883.
=> use --json-lines mode for list archive results for better parsing of unusual filenames

src/vorta/utils.py, tests/borg_json_output/diff_archives_dict_issue_stdout.json, tests/test_diff.py
- cause of error : defaultdict added more defaultdict while attempting to traverse the tree, but once a 'potential leaf' node was added, it was added as a dict, not a defaultdict.
example: (annotated output from 'borg diff --info --log-json repo::archive1 archive2')
added directory     home/rblenis/tmp/borgtest                              <-- 'home','rblenis','tmp' added as defaultdict, 'borgtest' added as dict
added       6.93 kB home/rblenis/tmp/borgtest/CircleFit.cpp       <-- 'CircleFit.cpp' added as dict
added       1.61 kB home/rblenis/tmp/borgtest/CircleFit.h           <-- 'CircleFit.h' added as dict
added directory     home/rblenis/tmp/borgtest/folder2                <-- 'folder2' added as dict
added       6.93 kB home/rblenis/tmp/borgtest/folder2/CircleFit.cpp   <-- …
=> fix issue #940 - KeyError in get_dict_from_list

src/vorta/tray_menu.py
XDG-compliant tray behavior: right click to open a context menu, and left click to restore the application.
If XDG_CURRENT_DESKTOP isn't set, always open the tray menu (macOS)
=> Open window on left-click. Fixes #938

src/vorta/borg/create.py, src/vorta/views/source_tab.py
We now refuse to add unreadable folders and .
warn about access errors during backup
Fixes #916
=> Refuse to add inaccessible folders, warn on inaccessible files during backup

src/vorta/views/diff_result.py, src/vorta/views/extract_dialog.py, src/vorta/views/partials/tree_view.py, tests/borg_json_output/list_archive_stdout.json
Fix for #915 . Folders are sorted with their type ('d') and not their size. It's a little first contribution (but I have deeply studied tree_view and extrac_dialog), so maybe it's not the better way to handle this issue. I don't understand why tests on archive tab are not passed from now on...
=> Fix for #915 . Folder ares sorted with type.

src/vorta/tray_menu.py
This PR fix #1030.
It was tested on : 
- i3 (Arch)
- sway / Wayland (Arch)
- Cinnamon (Mint)
- Unity (Ubuntu 20.04)
- Windows 10
The `aboutToShow` signal should be reliable on Mac as well (not tested).
=> Fix context menu not accessible on some setup

src/vorta/application.py, src/vorta/profile_export.py, src/vorta/views/main_window.py, tests/test_import_export.py
See #1053 for a description of the problem.
This solution catches all exceptions during bootstrap and prints them. The normal exception handler is not yet ready to show the error graphically so we do it ourselves.
While catching all exception is not considered good style I think it is justified in this case because the program should still be in an operable state if the import fails. Currently the program crashes silently on start rendering Vorta inoperable.
=> Show error dialog when .vorta-init.json is malformed (fixes #1053)

src/vorta/models.py, src/vorta/views/misc_tab.py
Fixes #1092 - This PR attempts to fix the autostart setting not being set correctly when importing. I deliberately chose not to duplicate the code from the misc tab to the init_db function. Instead I tried to keep it DRY and use signals from Pewee. This has the advantage that is does not matter where the SettingsModel is saved - the autostart is always set up afterwards.
This is only a suggestion how to fix it and I know that this is a bit different from an architectural point of view. We basically pull logic from a view to the models. I am always open to a different approach.
=> Always handle autosave setting when saving SettingsModel (fixes #1092)

src/vorta/scheduler.py
This fixes a situation where the schedule for a profile is disabled, but there are still jobs scheduled. Those need to be removed.
=> Remove jobs if scheduler setting is changed.

src/vorta/__main__.py, src/vorta/borg/borg_job.py, tests/conftest.py
=> DB Locking issues in BorgJob

src/vorta/views/utils.py
This is the warning to see with debug build of Python:
/usr/lib/python3.10/site-packages/vorta/views/utils.py:9: ResourceWarning: unclosed file <_io.BufferedReader name='/usr/lib/python3.10/site-packages/vorta/assets/icons/icon.svg'>
svg_str = open(get_asset(f"icons/{icon_name}.svg"), 'rb').read()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.10/site-packages/vorta/views/utils.py:9: ResourceWarning: unclosed file <_io.BufferedReader name='/usr/lib/python3.10/site-packages/vorta/assets/icons/unlink.svg'>
svg_str = open(get_asset(f"icons/{icon_name}.svg"), 'rb').read()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.10/site-packages/vorta/views/utils.py:9: ResourceWarning: unclosed file …
=> Close SVG files

src/vorta/autostart.py
Needed for Debian/`pybuild` tests. See #930
=> Create missing parents of autostart folder. See #930

src/vorta/views/partials/tree_view.py
I found that I wanted a diff view which would allow me to investigate unexpectedly large backups.  Since the size column was unused on the current diff view, and it seemed natural to me to have it be the sum of the size of the contained items, I made that change.
String compare is used when filtering because large diffs were taking too long with os.path.commonpath, which is more general than what we need here.
=> Diff view now shows folder sizes as sum of sizes of contained items

src/vorta/application.py, src/vorta/borg/borg_job.py, src/vorta/borg/check.py
In case the `BorgCheckJob` fails vorta switches over the returncodes and reacts accordingly.
Fixes #1143.
| returncode | meaning | behaviour |
---------------  | ------------| --------------|
0                 | success (logged as INFO) | ignored
1                 | warning (operation reached its normal end, but there were warnings – you should check the log, logged as WARNING) | `QMessageBox` with warning icon and text stating the warning message from borg
2                 | error (like a fatal error, a local or remote exception, the operation did not reach its normal end, logged as ERROR) | `QMessageBox` with error icon stating the error message from borg and `Consider repairing or recreating the repository soon to avoid missing data.`
128+N |killed by signal N (e.g. 137 == kill -9) | …
=> Distinguish different errors in case `borg check` failed.

.github/workflows/build-macos.yml
Python 3.9 is included in latest images of macos-10.15
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
=> Remove installing python

src/vorta/scheduler.py, src/vorta/views/schedule_tab.py, tests/test_schedule.py
Always update the label in the schedule tab that displays the next time to start a backup when the scheduler updates its timer.
Fixes #1116.
* src/vorta/scheduler.py (VortaScheduler): Add `schedule_changed` signal.
* src/vorta/scheduler.py (VortaScheduler.set_timer_for_profile): Emit `schedule_changed` signal.
* src/vorta/views/schedule_tab.py (ScheduleTab): Connect `draw_next_scheduled_backup` to `schedule_changed` signal.
=> Update label displaying next backup time.

.github/workflows/test.yml
The tool *flake8* used in the tests runs on github allows for ignoring specific codes. The default named in the [docs](https://flake8.pycqa.org/en/latest/user/options.html?highlight=ignore#cmdoption-flake8-ignore) are `E121,E123,E126,E226,E24,E704,W503,W504`, although these default reasonable it seems as if flake actually doesn't use them by default. I would therefore like to add them to the test runs.
=> Add reasonable, default ignores to flake8.

src/vorta/scheduler.py, tests/conftest.py, tests/test_scheduler.py
The scheduler will now react to a new fixed time also if 24h haven't passed yet.
All in all the code is supposed to be cleaner and easier understandable.
The logging was slightly modified.
I wrote some tests for the schedule routine itself, but there are still some test cases for the feature that catches up missed backups missing.
Fixes #1184 and fixes #1182.
=> Rewrite scheduler.

src/vorta/views/archive_tab.py
These translations will allow the strings to be translated to different languages, instead of showing them always in English.
=> Issue 1223 - Add missing translated strings on archive tab

src/vorta/views/source_tab.py
String now translates.
Fixes #1239
=> Resolves borgbase/vorta#1239

src/vorta/assets/UI/archivetab.ui
String ` Monthly`: starts with a space by mistake as reported by pavelb on [transifex](https://www.transifex.com/borgbase/vorta/translate/#cs/vorta/413641141).
* src/vorta/assets/UI/archivetab.ui
=> Fix string starting with a space in `archivetab.ui`.

src/vorta/assets/UI/sourcetab.ui, src/vorta/utils.py
The standard exclude pattern used by borg is *fnmatch*. 
* src/vorta/assets/UI/sourcetab.ui : Change `E.g. **/.cache` to `E.g. */.cache`.
* Use fnmatch to exclude files when calculating source stats.
=> Use fnmatch for exclude patterns.

src/vorta/assets/UI/archivetab.ui, src/vorta/utils.py, src/vorta/views/archive_tab.py, tests/test_archives.py
Fixes #1256.
* src/vorta/assets/UI/archivetab.ui : Rename `bMount` to `bMountArchive`.
* src/vorta/assets/UI/archivetab.ui : Add `bMountRepo`.
* src/vorta/views/archive_tab.py (ArchiveTab): Rename `bMount` to `bMountArchive`.
* src/vorta/views/archive_tab.py (ArchiveTab): Implement behaviour for `bMountRepo`.
Add `repo_mount_point` attribute.
* src/vorta/views/archive_tab.py (ArchiveTab): Add tooltips to `bMountArchive`.
* src/vorta/views/archive_tab.py (ArchiveTab): Adjust `mount_action` and `unmount_action` to
mount and unmount the full repository as well.
* src/vorta/utils.py (get_mount_points): Also search for full repo mounts.
=> Add a button to mount whole repository.

src/vorta/store/settings.py
Currently on systems with system tray support the user has no idea what this setting does.
* src/vorta/store/settings.py (get_misc_settings)
Suggestions for a better (especially shorter) wording are welcome!
=> Rewrite label of `enable_background_question` to be understandable.

src/vorta/keyring/secretstorage.py
Some password managers (like KeePassXC) will lock an SecretStorage item behind a manual user approval dialog even when the collection is already unlocked. This prevents Vorta from using SecretStorage compatible password managers that exhibit this behavior.
This pull request fixes the way an item is obtained so any manual user approval dialog is triggered.
=> SecretStorage: Unlock item if it is locked. Fixes #1232 and #1233.

src/vorta/borg/delete.py, src/vorta/borg/prune.py, src/vorta/views/repo_tab.py
Fixes #338.
* src/vorta/views/repo_tab.py (RepoTab.init_repo_stats): Cope with stat value `None`.
* src/vorta/borg/delete.py (BorgDeleteJob.finished_event): Set stats to `None`.
* src/vorta/borg/prune.py (BorgPruneJob.finished_event): Set stats to `None`.
=> Set repo stats to `N/A` after deleting an archive or pruning a repo.

src/vorta/views/archive_tab.py
When adding the repo mount button `bMount` was renamed to `bMountArchive`. Though updating of a few references was forgotten.
Therefore requesting the context menu of the archive list raises an error.
* src/vorta/views/archive_tab.py (ArchiveTab)
=> Replace `bMount` with `bMountArchive`.

src/vorta/scheduler.py
Fixes #1286.
* src/vorta/scheduler.py (set_timer_for_profile): Return if repo is not set. (Return statement was missing)
=> Don't schedule backup if repo isn't set.

src/vorta/i18n/__init__.py, src/vorta/scheduler.py, src/vorta/views/schedule_tab.py, tests/conftest.py, tests/test_schedule.py, tests/test_scheduler.py
A backup will only be scheduled if there already was a previous backup for this profile.
The `Next backup time` status label now supports more than two messages. It can show `None scheduled`, `Run a manual backup first` and the scheduled time **in the format of the translation locale**.
Fixes #1291.
* src/vorta/scheduler.py (VortaScheduler.\_\_init\_\_): Connect `VortaApp.backup_finished_event`
to `set_timer_for_profile`.
* src/vorta/scheduler.py (VortaScheduler.set_timer_for_profile): Only schedule if there was a previous backup.
* src/vorta/scheduler.py (VortaScheduler.set_timer_for_profile): Emit `schedule_changed` also when no backup is scheduled.
* src/vorta/scheduler.py: Add `ScheduleStatusType` and `ScheduleStatus` representing
the scheduler status  for a profile.
* …
=> Only schedule backup after a manual one.

src/vorta/borg/borg_job.py, src/vorta/scheduler.py
Fixes #1293 and #1289.
* src/vorta/scheduler.py (VortaScheduler): Implement `pause` to call a timeout
on the scheduler for a profile as well as `unpause`.
* src/vorta/scheduler.py (VortaScheduler.notify): Pause/unpause scheduler if a
backup fails/succeeds.
=> Pause scheduling for a profile temporarily if a backup fails.

Makefile
Makefile (translations-from-source): Use a call to `find` to get a list
of source files (*.ui and *.py) that is passed to `pylupdate5`.
=> Determine source files for `translations-from-source` dynamically.

src/vorta/assets/UI/archivetab.ui
Addendum to #1176. Fixes input field width on macOS. Missed this when fixing the same for the scheduler tab.
Before:
After:
=> Fix macOS input form size

src/vorta/i18n/__init__.py, tests/test_schedule.py
The `language` method was added with Qt 5.15, which not all linux distributions use yet.
* src/vorta/i18n/__init__.py (get_locale): Return the global locale.
*That's a disadvantage of using a clean test system: You won't notice such issues.*
=> Remove call to `QTranslator.language()` in `get_locale`.

src/vorta/views/diff_result.py
Currently an assert statement checks whether a change type was recognized.
This assert statement won't give any information on the actual change type that
is not implemented. Now a ValueError that mentiones the unknown change type in
its message will be raised instead. This will help debugging future problems but also present ones like #1347.
* src/vorta/views/diff_result.py (parse_diff_json_lines): Replace assert statement by
if and raise statements.
=> Raise `ValueError` in case of unknown change type in diff json.

src/vorta/views/diff_result.py
This should help debugging errors like #1347.
* src/vorta/views/diff_result.py (parse_diff_json_lines): Before raising ValueError for unknown change type,
log the diff line with level ERROR.
=> Log json diff line if there was an error parsing it.

.gitattributes, tests/test_misc.py, tests/test_repo.py
* tests/test_misc.py
* tests/test_repo.py
* .gitattributes : Set `diff` mode for `.py` files to python.
=> Add spaces after `assert` and enhance git py diff.

src/vorta/borg/borg_job.py, src/vorta/borg/create.py, src/vorta/borg/extract.py
Closes #1383
This only has been tested locally, but seems to work. The file is only cleaned in case of a success
=> cleanup temp files at end of job

.github/workflows/test.yml
This shows linting as first github action check for commits and PRs. Before you always had to scroll down past all the test for different python and os versions.
=> Move linting to the top in test.yml

src/vorta/borg/prune.py
* src/vorta/borg/prune.py (BorgPruneJob.prepare): Use `-a prefix*` instead of `--prefix prefix` for V2.
=> Update use of `--prefix` for borg V2.

src/vorta/assets/UI/archivetab.ui, src/vorta/views/archive_tab.py
Resolves #1398.
* src/vorta/assets/UI/archivetab.ui (bCheck): Fix typo.
* src/vorta/assets/UI/archivetab.ui (compactButton): Add tooltip.
* src/vorta/assets/UI/archivetab.ui (bDelete): Fix typo.
* src/vorta/views/archive_tab.py (on_selection_change): Fix tooltip for `bMountArchive`.
* src/vorta/views/archive_tab.py (bmountarchive_refresh): Fix punctuation and set tooltip correctly. Add option for setting the icon only.
* src/vorta/views/archive_tab.py (bmountrepo_refresh): Fix punctutation.
* src/vorta/views/archive_tab.py (set_icons): Refresh only the icon of `bMountArchive`.
=> Check-strings

src/vorta/assets/UI/repotab.ui, src/vorta/views/repo_tab.py
Fixes #1400.
* src/vorta/assets/UI/repotab.ui : Name `frameRepoSettings` and `layoutSSHKey`.
* src/vorta/views/repo_tab.py (RepoTab.init_repo_stats): Disable `frameRepoSettings` if no repo is selected.
Disable widgets in `layoutSSHKey` in case of a local repository except from `bAddSSHKey` so the
the user can add a key for a adding a repo.
=> Disable ssh key option in repo tab for local repos.

src/vorta/utils.py
This should help debugging #1304.
=> Log the error when parsing a file in `~/.ssh` fails.

src/vorta/borg/borg_job.py, src/vorta/views/repo_tab.py, tests/test_repo.py
First element with index 0 is always the 'unset' option with data `None`. Label is `No repository selected`.
Fixes #1428.
* src/vorta/views/repo_tab.py (RepoTab.set_repos): Add element.
* src/vorta/views/repo_tab.py (RepoTab.repo_unlink_action): Handle the first element as unset.
* src/vorta/views/repo_tab.py (RepoTab.copy_URL_action): Handle unset state.
=> Add default `unset` value to repo combobox.

.github/workflows/build-macos.yml, .github/workflows/test.yml
The second version of the checkout action is deprecated and won't be supported by Github Actions in the future because it uses Node.js 12.
=> Update `acions/checkout` to v3.

src/vorta/borg/prune.py
With borg v2.0.0b3 the default pattern style was changed to identical matching.
* src/vorta/borg/prune.py (BorgPruneJob.prepare)
=> Specify the use of a `sh:`-style pattern when pruning with borg v2.

src/vorta/__main__.py
Currently the link will open an empty issue. Now the user can choose one of the templates.
* src/vorta/__main__.py : Replace link.
=> Link to report form chooser in case of critical errors.

src/vorta/views/main_window.py, src/vorta/views/repo_tab.py, tests/test_repo.py
Fixes #1462.
* src/vorta/views/repo_tab.py (init_repo_stats): Remove *unset* item from combobox.
* src/vorta/views/repo_tab.py (populate_from_profile): Move into `populate_repositories`.
* src/vorta/views/repo_tab.py populate_repositories -> populate_from_profile
* src/vorta/views/main_window.py
=> Remove *unset* repository value from combobox when a repo is selected.

src/vorta/borg/list_archive.py
Fixes  #1474.
In python `+` takes precedence over the `if-else` operator.
Therefore brackets are needed around the latter.
* src/vorta/borg/list_archive.py (BorgListArchiveJob.prepare)
This also reverts an unwanted modification introduced in 0188b75.
* src/vorta/borg/list_archive.py (BorgListArchiveJob.prepare)
=> Fix extract

src/vorta/borg/extract.py
Fixes #1488.
Closing deletes the temp file. Closing is already done by `BorgJob.run` after running the command.
* src/vorta/borg/extract.py (BorgExtractJob.prepare): Remove call to `close` of temporary file.
*I provide my contribution under the terms of the [license](./../../LICENSE.txt) of this repository and I affirm the Developer Certificate of Origin.*
=> Don't close temp file before running `borg extract`.

src/vorta/views/repo_tab.py
Fixes #1495.
* src/vorta/views/repo_tab.py (RepoTab.__init__): Move call to `populate_from_profile` from the beginning to the end.
=> Populate repo info from profile after populating dropdowns.

src/vorta/scheduler.py
Schedules get missed, if system has been in hibernation/sleep state as described in [#1214](https://github.com/borgbase/vorta/issues/1214) Although, timers should be refreshed every 15min, it seems that all timers get deranged by sleep state and schedules is still missed in most cases. This seems to be a general issue with the underlying QTimer implementation.
This fix doesn't distinguish host OS and has only by tested on Linux. If 'org.freedesktop.login1.Manager' is not available, Vorta simple doesn't get notified if system awakes again. So no impact on other OS is expected
=> Restart timers after hibernation/sleep

src/vorta/borg/borg_job.py
Fixes #1509.
* src/vorta/borg/borg_job.py : The error will be discarded.
=> Catch `ProcessLookupError` in `BorgJob.cancel`.

src/vorta/views/main_window.py
Before a float was passed to `QPoint(int, int)`. While this worked fine, on some machines it lead to an error. Fixes #1535.
* src/vorta/views/main_window.py : cast division value to int.
=> Pass int to `QPoint` constructor.

src/vorta/borg/compact.py
It's nice to have status updates during compacting, as it can take a while to compact a large repository if it hasn't been done in a while. As an example, compacting my 10 TB backup for the first time took half an hour, so it was nice being able to see the progress.
=> Show status updates while compacting

src/vorta/borg/create.py, tests/test_create.py
Backups will run although no sources are specified if `--paths-from-command` is supplied. Also arguments after `--` will be appended to the end of the command after all other arguments. Closes #1537.
* src/vorta/borg/create.py
=> Add support for `--paths-from-command` to extra borg arguments.

src/vorta/tray_menu.py
The menu is build ones before the tray icon is clicked so that it is registered correctly.
Fixes #1206.
* src/vorta/tray_menu.py (TrayMenu): Rename `on_user_click` to `build_menu`.
* src/vorta/tray_menu.py (TrayMenu.__init__): Call `build_menu`.
=> Fix tray menu on XFCE.

requirements.d/dev.txt, setup.cfg
I'm far from being an expert, but it seems `pip` is not necessary in `setup_requires` as per this [suggestion](https://github.com/void-linux/void-packages/pull/41672#discussion_r1071176890).
Also, testing fails complaining about missing module `six`. Could you please check it out?
=> Fully remove setup_requires, pin black 

src/vorta/views/repo_tab.py
Fixes #1579
As discussed in the issue, I am not sure that this fix is the most relevant — it only makes the "+" button for SSH keys available at all times, in order to be able to bootstrap a remote backup without having to run `ssh-keygen` manually (eg. for non-tech users). A quickstart wizard, or even a similar "+" option in the repository creation dialog itself, would be better suited, I believe.
=> Allow creating an SSH key when bootstrapping Vorta

.pre-commit-config.yaml
A new version of Poetry broke isort which caused errors when running pre-commit.
Running the command `pre-commit autoupdate` updates the configuration to use the newest isort, which has a hotfix for the bug. It also updates pre-commit, black, and flake8 as a side-effect.
https://github.com/borgbase/vorta/issues/1600
It fixes the pre-commit checks
I ran pre-commit and it works, when it hasn't before
=> Modify pre-commit config file using autoupdate

src/vorta/views/repo_tab.py
Previously this button would only work if you had more than one SSH key which prevents the first one from being copied.
This simple change allows copying the public part of the first ssh key, which wasn't accessible previously due to the if check failing on index 1 (which could be a valid key).
Steps to reproduce:
* Have only one SSH key available.
* The dropdown should list _"Auto"_ and then _"somekey (ssh-rsa)"_
* Select the _"somekey (ssh-rsa)"_
* The "Copy to Clipboard" function doesn't work, and asks you to select a key - despite you having selected one.
I only have one ssh key registered in Vorta usually, so it's annoying that I can't use the "Copy to Clipboard" functionality to test the key.
I tested this via a local dev environment. The change is so extremely simple I can't …
=> Allow copying the public part of the first SSH key

src/vorta/assets/icons/help-about.svg, src/vorta/store/connection.py, src/vorta/store/migrations.py, src/vorta/store/models.py, src/vorta/store/settings.py, src/vorta/views/misc_tab.py, src/vorta/views/partials/tooltip_button.py, tests/test_misc.py
Fixes #1517
* src/vorta/store/models.py (SettingsModel): Add `tooltip` column.
* src/vorta/store/migrations.py (run_migrations): Create `tooltip` column.
* src/vorta/store/connection.py (init_db): Populate `tooltip` column. Increase `SCHEMA_VERSION`.
* src/vorta/views/misc_tab.py (MiscTab.populate): Set tooltip of checkbox widgets.
* src/vorta/store/settings.py : Add tooltips and update label of `override_mount_permissions`
=> Add tooltips to settings.

src/vorta/borg/borg_job.py, src/vorta/borg/create.py
=> feat: more descriptive messages when no sources are selected to backup

src/vorta/application.py, src/vorta/borg/borg_job.py, src/vorta/borg/break_lock.py, src/vorta/borg/check.py, src/vorta/borg/compact.py, src/vorta/borg/create.py, src/vorta/borg/delete.py, src/vorta/borg/diff.py, src/vorta/borg/extract.py, src/vorta/borg/info_archive.py, src/vorta/borg/list_archive.py, src/vorta/borg/list_repo.py, src/vorta/borg/prune.py, tests/test_archives.py, tests/test_lock.py, tests/test_repo.py
Append profile name to every log message
#1379 
Helps the user know which profile the log is coming from.
=> feat: add profile name to log messages

src/vorta/borg/_compatibility.py, src/vorta/borg/diff.py
[Borg 1.2.3 -> 1.2.4](https://github.com/borgbackup/borg/compare/1.2.3...1.2.4) introduced [--content-only](https://github.com/borgbackup/borg/pull/7414) which crashes vorta on diff action when files have metadata changed. This PR adds `--content-only` flag to diff command for this borg version.
Fixes #1668
=> Added --content-only flag for borg 1.2.4 in diff view

src/vorta/borg/_compatibility.py, src/vorta/borg/diff.py, src/vorta/views/diff_result.py, tests/test_diff.py
Implements *ctime* and *mtime* diff types added in borg 1.2.4.
Resolves #1672
Added handling for *ctime* and *mtime* diff and will show changes in tooltip in archive diff window.
https://github.com/borgbase/vorta/issues/1672
Prevents crash on borg >= 1.2.4
Tested on borg 1.2.4 and added tests for handling *ctime* and *mtime*.
=> Handle ctime and mtime diff changes

src/vorta/borg/extract.py
(Hopefully) fixes #1623.
* src/vorta/borg/extract.py : The pattern file passed to borg now contains `pf`-style patterns for included paths.
=> Use `pf` pattern format for specifying what to extract.

src/vorta/store/settings.py, src/vorta/views/archive_tab.py, src/vorta/views/diff_result.py, src/vorta/views/extract_dialog.py, src/vorta/views/partials/treemodel.py
Added two settings to remember user's preferred files list view in the diff and extract dialogs
- `extract_files_display_mode`
- `diff_files_display_mode`
fixes #1516 
Improves UX
Tested by changing the views and reopening vorta.
I have to update the tests, then I'll make this ready for review.
=> feat: add settings for files list views

setup.cfg
Seems like we forgot to remove this.
@m3nu after you merged this, could you please create another point release?
=> Remove paramiko from dependencies

src/vorta/assets/UI/archivetab.ui, src/vorta/utils.py
Before, using `{hostname}` as archive or prune name template may include the network domain, like `.local` or `.fritzbox`. This can interfere with pruning and generate different archive names.
With this PR, only the short hostname will be used and `fqdn` is added as option.
Fixes #1696
=> Make {hostname} name template consistent with Borg, add {fqdn} template option

.github/workflows/test.yml, setup.cfg, src/vorta/autostart.py, src/vorta/keyring/darwin.py, src/vorta/notifications.py
Moved pyobjc imports to modul level, since lazy imports would cause a segfault starting with version 9.1
Also set minimum Python version to 3.8 and removed pinning of GH Action's Python action.
Fixes #1695 
=> Fix pyobjc imports, bump minimum Python version

.github/actions/setup/action.yml, .github/workflows/test.yml, Makefile
Fixes #1709 
Instead of running black, flake8 and ruff the lint phony now runs pre-commit which has these tools configured as hooks.
* Makefile
* .github/actions/setup/action.yml
* .github/workflows/test.yml
Updated to v3
* .github/workflows/test.yml
=> Run pre-commit in lint ci and polish ci setup.

.github/ISSUE_TEMPLATE/feature_request.md, .github/stale.yml
This uses a different, maintained version of stale bot with the same settings.
In addition, I removed auto-tagging certain issues, since this should be up to maintainers. Only after an issue is accepted, it should be tagged.
Fixes #1715
=> Use maintained stale action

Makefile
Fix the location of the Sparkle Caskroom location on macOS.
Homebrew's Caskroom moved from /usr/local to /opt/homebrew with the release of Apple Silicon, /usr/local is now only used for older Intel based machines.
This Makefile change detects if the machine is ARM based and if so sets the correct homebrew location.
This allows Vorta to build locally where previously it would error out.
- #727 
Otherwise you can't build Vorta on modern macOS machines.
I've run it on two machines, both worked as expected.
N/A
- [-] My change requires a change to the documentation.
- [-] I have updated the documentation accordingly.
- [-] I have added tests to cover my changes.
- [-] All new and existing tests passed.
*I provide my contribution under the terms of the [license](./../../LICENSE.txt) of this …
=> fix(makefile): Correct homebrew path on modern macOS machines

tests/integration/conftest.py, tests/integration/test_archives.py, tests/integration/test_borg.py, tests/integration/test_repo.py, tests/unit/conftest.py, tests/unit/test_archives.py, tests/unit/test_diff.py
It is possible to reduce code duplication in the archive unit tests by using a fixture to handle repeated setup. Additionally, there are a some archive_tab methods that still needed testing. In this PR, I aim to solve both of these issues.
#1754 
One of my Google Summer of Code projects involves cleaning up the Vorta tests, reducing duplicated code, and increasing code coverage.
Tests work locally by running pytest, and they pass the GitHub CI checks.
=> PR: `tests/unit/test_archives`: reduce code duplication and increase test coverage

tests/unit/test_archives.py, tests/unit/test_diff.py
There are some areas of opportunity in the `diff_result` module for increased test coverage of some class methods and functions. The `test_diff` module is already well parametrized and does not have a notable amount of code duplication, so here I would like to focus mainly on increasing code coverage.
#1754 
One of my Google Summer of Code projects involves cleaning up the Vorta tests, reducing duplicated code, and increasing code coverage.
Tests work locally by running pytest, and they pass the GitHub CI checks.
=> PR: `tests/unit/test_diff`: increase test coverage

src/vorta/views/source_tab.py, tests/unit/test_source.py
In this PR, I cleaned up the `test_source` module by splitting the `paste_text()` testing into its own separate test. I then parametrized `test_paste_text()` to cover more use/edge cases. Finally, I added in tests for removing a source from the sources table, as well as testing the source update button.
#1754 
One of my Google Summer of Code projects involves cleaning up the Vorta tests, reducing duplicated code, and increasing code coverage.
Tests work locally by running `pytest`, and they pass the GitHub CI checks.
=> PR: `tests/unit/test_source`: cleanup, parametrize, and increase test coverage

.github/scripts/generate-matrix.sh, .github/workflows/test.yml
#1778 
#1754 
@m3nu , @jetchirag , @real-yfprojects 
=> PR: Reduce test workflow for each PR/commit

src/vorta/store/settings.py
For Issue #1763 
- [x ] New feature (non-breaking change which adds functionality)
- [ x] I have read the [CONTRIBUTING](https://vorta.borgbase.com/contributing/) guide.
- [x ] My code follows the code style of this project.
=> changed label and tooltip for startup of Vorta

src/vorta/views/archive_tab.py, tests/unit/test_archives.py
Fixes #1790 
Improved stability during background operations.
I edited the current archive rename unit test to ensure it asserts the rename button is enabled before attempting the rename.
Passes tests locally and on GitHub workflow.
=> Prevent in-line archive rename during ongoing operation

src/vorta/assets/UI/archivetab.ui, src/vorta/views/archive_tab.py
The context menu that appears when you right click on an archive has its own rules for when actions are enabled or disabled, separate from the rules for the buttons in the archive tab, even though they perform the same actions. I do not believe there is a reason for these buttons to ever be enabled in the context menu and disabled on the archive tab or vise versa.
In this PR, I have bound the "enabled" or "disabled" state of the actions in the archive right-click context menu to the state of their button equivalent in the archive tab. This will improve consistency, and prevent issues like the one I encountered [here](https://github.com/borgbase/vorta/issues/1792).
#1792 
Improve consistency and prevent errors
Tested locally, and passes Github test workflow
*I provide my contribution under …
=> Bound archive buttons enable/disable to context menu actions

src/vorta/views/repo_tab.py, src/vorta/views/ssh_dialog.py, tests/unit/test_repo.py
Issue described here: #1801 
In addition to fixing the issue of adding keys to the dropdown right away, I tweaked the process for adding a key such that now when the user adds a new key, they receive a QMessageBox alert informing them and the SSH dialogue box closes. Previously, the SSH dialogue box would not close unless the user clicked 'cancel', which seems counterintuitive. Here is a demo of the changes:
#1801 
Greater consistency and (hopefully) improved user experience.
Locally
=> 'Add SSH Key' Improvements

setup.cfg
4.x is backwards compatible with 3.x except that site_cache_dir has moved to /var/cache. Vorta doesn't use this.
https://github.com/platformdirs/platformdirs/releases/tag/4.0.0
N/A
Debian is applying this patch so it can carry platformdirs 4.
Ran the test suite as part of a Debian build.
N/A
=> Loosen platformdirs dependency

src/vorta/store/connection.py
Creates a backup copy of settings.db before migrations
Fixes #1641
Tested by creating a copy on `init_db()`
=> Backup settings.db before migrations

.github/ISSUE_TEMPLATE/bug_form.yaml, .github/ISSUE_TEMPLATE/bug_report.md, .github/pull_request_template.md, noxfile.py, package/fix_app_qt_folder_names_for_codesign.py, src/vorta/application.py, src/vorta/borg/jobs_manager.py, src/vorta/network_status/abc.py, src/vorta/profile_export.py, src/vorta/scheduler.py, src/vorta/views/archive_tab.py, src/vorta/views/diff_result.py, src/vorta/views/partials/treemodel.py, src/vorta/views/profile_add_edit_dialog.py, src/vorta/views/repo_tab.py, src/vorta/views/source_tab.py, tests/unit/test_treemodel.py
most stuff was found by pycharm code checker.
commit 48af51f should fix some potential malfunction, that function is called without params rather often, thus site=None -> bug.
=> random cleanups / fixes

src/vorta/views/schedule_tab.py
Allowing a network from the list currently fails due to changed enum comparison. This should have been changed during our Qt6 migration.
=> Fix issue after Qt6 migration to save allowed Wifis

setup.cfg, src/vorta/network_status/darwin.py, tests/network_manager/test_darwin.py
This change addresses #1884 by adding support for Vorta to detect when macOS is connected to a Wi-Fi network presented by an iOS Personal Hotspot.
I changed how the `darwin` module gets its information about Wi-Fi networks to use ObjC instead of running command line tools.  The benefits of using the ObjC Cocoa APIs is that we get richer information about Wi-Fi networks. There is an explicit API in Cocoa for checking whether a connected Wi-Fi network is an iOS Personal Hotspot. 
I left the existing implementation in place, and added a new check for iOS since it seems like the previous implementation was working when tethered with an Android device.
* #1884 
I updated this part of the code base because while I was working through an home Internet outage recently, a Vorta backup running in …
=> Detect metered connections for macos when connected to an iOS Personal Hotspot

src/vorta/assets/metadata/com.borgbase.Vorta.appdata.xml
Flathub is getting more and more strict when it comes to metadata. 
I've added "Vorta developers", I can also be more specific if people prefer that.
=> Add developer name to appdata

src/vorta/tray_menu.py
This sorts the profile names alphabetically in the `Backup Now` item of the tray menu.
=> Sort profiles in the Backup Now tray menu

src/vorta/scheduler.py
Made changes to notify function to deliver notifications based on the status of post_backup_tasks. Post Backup Tasks include pruning as well as BorgCheckJob(data consistency check)  as referred to in the issue.  This way user isnt spammed with different notifications and still notified for post backup jobs
Fixes #1632 
A notification for when post backup jobs were completed, earlier only a log for completion of these jobs was delivered. Now a status based notification is delivered
Backups were scheduled and after completion of post_backup_jobs expected notifications were delivered. 
=> Notify after post_backup_tasks #1632

src/vorta/tray_menu.py, src/vorta/views/main_window.py
Creating a new profile adds the new profile at the bottom of the list in the main window. Similarly, editing an existing profile doesn't change its position in the list. This change keeps the list sorted alphabetically in both cases.
Fixes #1983
=> Keep the profile list sorted when creating/renaming profiles

src/vorta/views/partials/password_input.py, src/vorta/views/repo_add_dialog.py
Hides the password fields in repo_add_dialog if _Advanced > Encryption: None_
#1995 
Helps avoid confusion if a password is needed or not.
Tested by me locally.
=> hide password field if encryption is none

src/vorta/assets/exclusion_presets/dev.json
This adds a preset to exclude the .flatpak-builder directory on linux.
when you build flatpaks with flatpak-builder there is gonna be directory that contains libraries, cached files, compiled binaries etc. on a per project basis. This is obviously data that is relatively useless to backup.
This is gonna exclude every directory called .flatpak-builder anywhere on the filesystem.
it can get really big in size
for vorta it is like 400MiB
for some rust gui apps for example a couple of gigs 
I forked the repo made the necessary changes and built the flatpak from master branch and ran a backup of a git folder that I knew has a .flatpak-builder directory and it is not there in the archive.
*I provide my contribution under the terms of the [license](./../LICENSE.txt) of this repository and I …
=> add flatpak builder cache exclude preset

src/vorta/assets/UI/scheduletab.ui, src/vorta/scheduler.py, src/vorta/store/connection.py, src/vorta/store/migrations.py, src/vorta/store/models.py, src/vorta/views/schedule_tab.py
Allows users to run `borg compact` after specified intervals. Added 2 columns to the profile model: `compaction_on` to check/uncheck scheduling, and `compaction_weeks` to set interval in weeks. Default interval set to 3 weeks.
Resolves #1718 
Backup space usage is exploding for some people until they realize they have to run compact manually. This allows users to schedule running compact just like validation.
Tested manually by setting `compaction_cutoff`  to minutes instead of days in `scheduler.py`.
=> Compaction Scheduling

src/vorta/profile_export.py, tests/unit/test_profile.py
Removes duplicate source files when importing an existing profile and choosing to overwrite. Based on PR by @TheLazron .
Fixes #1942 
Tested locally.
=> Remove duplicate sources on profile import

.github/ISSUE_TEMPLATE/bug_form.yaml, .github/ISSUE_TEMPLATE/bug_report.md
Updated the path for viewing logs/ Vorta and Borg versions in the GitHub Issue Template to reflect new UI.
=> Update Log path in Issue Template

src/vorta/assets/UI/sourcetab.ui, src/vorta/views/source_tab.py
Enabled grid and alternating row colors in Sources table to match the design of Archives table.
=> Sources table UI updated to match Archives table

src/vorta/utils.py
Split `get_mount_points` into multiple methods to reduce nested elif statements and improve readability.
=> Refactor get_mount_points

src/vorta/views/schedule_page.py, src/vorta/views/schedule_tab.py
Moved `palette_changed` connection from schedule_page.py to schedule_tab.py, where `set_icons()` is defined.
Resolves #2048 
Could not test as changing themes does not work on my system.
=> palette_changed connection moved to schedule_tab

src/vorta/views/main_window.py
Fix the main window icon on Wayland
On Wayland, calling `setWindowIcon()` to set the window icon is no longer supported, the correct way is to call `setDesktopFileName()` instead. The desktop file is then used to load the correct icon.
See https://doc.qt.io/qt-6/qguiapplication.html#desktopFileName-prop and https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon for more information.
Before:
After
=> Fix generic window icon on Wayland

src/vorta/assets/metadata/com.borgbase.Vorta.desktop
* Previous value didn't match the value of the running application
* With this mismatch the icons were not applied correctly in at least GNOME DE
Tested by setting the changes in the already installed app. Not tested by building the app.
Added attribute to .desktop file
- [] My change requires a change to the documentation.
=> Fixed missing icons in GNOME Overview and GNOME Dock

src/vorta/store/settings.py
String is not appearing on Transifex, so tried to modify its form based on ones, which does.
=> l10n - make string translatable (syntax fix)

src/vorta/assets/exclusion_presets/browsers.json
I have taken the exclusions from the existing firefox set, and matched them with those files that exist in the Snap package. Based on the Snap in KDE Neon.
Only one file modified.
(https://github.com/borgbase/vorta/issues/2085)
The existing presets to exclude firefox cache files cover flatpaks but not Snaps. I added them manually to my own backup exclusions but I think they are probably more widely applicable.
Not in this format; the exclusions are those I use already and the formatting seems to be simple enough to not be very concerning. (Famous last words?)
N/A
=> Exclusion presets: add Firefox Snap Cache

src/vorta/application.py, src/vorta/views/archive_tab.py, src/vorta/views/log_page.py, src/vorta/views/main_window.py, src/vorta/views/misc_tab.py, src/vorta/views/networks_page.py, src/vorta/views/repo_tab.py, src/vorta/views/schedule_page.py, src/vorta/views/shell_commands_page.py, src/vorta/views/source_tab.py
This uses Qt signals instead of calling child widgets and their `populate_from_profile()` method.
Fixes #1962
Replaces #1964
=> Use events instead of calling child widgets

src/vorta/borg/_compatibility.py
`borg --version` may run after the first backup. To avoid errors with zstd, we assume a Borg version that supports Zstd.
There is a risk that the user is actually using an old Borg version, but in that case, he shouldn't be able to select zstd anyways.
Fixes #2129
Fixes #2139
=> Assume newer Borg version, in case check runs after first backup.

src/vorta/borg/borg_job.py
Override the $PATH environment variable on the MacOS (Darwin) platform, so that homebrew-provided native binaries for Borg will be used, rather than falling back to the built-in Borg binary.
https://github.com/borgbase/vorta/issues/2100
For an unknown reason (see linked issue above), the PyInstaller approach to setting the PATH variable does not appear to function any more - Vorta on ARM with a homebrew-installed native borg binary will not find that binary. Debugging shows the PATH variable is set wrongly, and will never find a binary in /opt/homebrew/bin. This patch will change that.
1. Debugging statements added around existing areas of code (see linked issue) to establish the PATH being used
2. Tested with this change and observed the homebrew based binary was found and shown in …
=> Override $PATH for MacOS to find native homebrew borg binaries (#2100)

src/vorta/assets/UI/repo_add.ui, src/vorta/views/partials/password_input.py, src/vorta/views/repo_add_dialog.py
This PR adds more clarity to passphrase field of "Add new repository" and "Add existing repository" sections.
Changes made:
-  Added placeholder text in passphrase field for better clarity for the users.
- Added a NOTE section to notify the importance of keeping the entered passphrase safe.
- UI of `repo_add.ui` has been modified.
- No existing functionality has been changed.
Resolves #2194
Several users reported confusion regarding the passphrase field in the "Add new repository" of Vorta and requested an improved UI with clearer information.
- Tested the UI by running the build
=> Improved GUI to clarify the passphrase field

src/vorta/notifications.py
This PR removes the timeout for error notifications in the Vorta. Instead of disappearing after 5 seconds, error notifications will remain until the user dismisses them manually. 
```python
time = 0 if level == 'error' else 5000
```
This ensures that the user has a better chance to review critical error messages and take necessary actions, even if they don't see the notification immediately.
Resolves #2045 
Tested on Linux Mint 22.1
Testing was done by calling the notification class `DBusNotifications`
```python
if __name__ == "__main__":
from unittest.mock import MagicMock
SettingsModel.get = MagicMock(return_value=MagicMock(value=True))
notifier = DBusNotifications()
notifier.deliver('Test Notify', 'This is a test notification', level='error')
print("Test Notification ran...")
```
*I …
=> Notification timeout removed for critical errors

src/vorta/utils.py
The Python os.stat() function below throws an unhandled OSError exception if the file being read's path length exceeds what the OS allows (e.g. 255 on Win7, 1024 on Mac).
https://github.com/borgbase/vorta/blob/0a316e7aa9ae8e61ff3a1e72dcd57c8a2b7976da/src/vorta/utils.py#L116-L125
fixes https://github.com/borgbase/vorta/issues/2115
Currently, the whole application will crash when estimating backup size if a single file (even if it's excluded) exceeds the maximum length allowed by the OS. PR https://github.com/borgbase/vorta/pull/2206 addresses excluding files from being calculated as part of the backup size, and this PR ignores files that have an excessive path length.
I've run the pytest and pre-commit tests and they have passed.
I'm unable to manually test this as MacOS will not allow me …
=> Skip reading file size if path name is too long

src/vorta/borg/create.py
Shows the correct status after a backup is finished.
I'm guessing the issue is that we run another task after emitting the 'finished' event.
Fixes #2120
=> Re-arrange tasks to get correct finished event

src/vorta/assets/icons/home.svg, src/vorta/filedialog.py, src/vorta/views/source_tab.py, tests/unit/test_filedialog.py, tests/unit/test_source.py
Currently, in Vorta, we use two separate file selectors for selecting files and folders due to limitations in Qt. This PR introduces a unified file selector made with `QTreeView` that:
- Allows the selection of multiple files and folders simultaneously, addressing https://github.com/borgbase/vorta/issues/1869
- Replaces the two separate selectors with a single, unified dialog
Solves #1869
Due to limitations in the Qt, we previously had to rely on separate dialogs for files and folders, which created a confusing and less efficient user experience. This PR improves usability and code maintainability by replacing them with a new single selector.
As of now, manual UI testing has been performed to verify the new selector works as expected. Existing test cases may currently fail due to new …
=> Add a new unified file selector

src/vorta/assets/exclusion_presets/temp.json
On temp.json, added a few more patterns to the "All Cache File" exclusion preset. Excluded directories:
-  *Cache dirs (though listed without a wildcard to avoid greedy matching);
-  .ld.so library linking cache;
-  tmp dir.
#2230 
Going to Sources > Manage Excluded Items... > Presets and selecting "All Cache Files", Flatpak application caches are still included in backup. This fixes that.
I've tested this by adding the proposed changes to the "Raw" exclusion patterns tab. I've also tested manually removing the dirs from a few few Flatpak apps and they regenerated these without issue on their next run.
None.
[dco]: …
=> Adding Flatpak app caches to "All Cache Files" exclusion preset.

src/vorta/views/archive_tab.py, src/vorta/views/exclude_dialog.py
This PR fixes the blank item that was getting added in the Custom tab of the Exclusion dialog. Even though the blank entry was getting discarded in GUI, it stayed when reopening the dialog. The reason being, the item was added to the database as a blank entry right when it was created.
A condition check was added to check if the entry is not blank before adding to the database.
Fixes #2267
Fixes https://github.com/borgbase/vorta/issues/2134 (Unrelated bug fix)
The fix has been tested with the GUI.
=> Fix the blank entry in the Custom exclusion
