setup.cfg
src/vorta/application.py
src/vorta/borg/borg_thread.py
src/vorta/borg/create.py
src/vorta/borg/info.py
src/vorta/borg/init.py
src/vorta/borg/list.py
src/vorta/models.py
src/vorta/notifications.py
src/vorta/scheduler.py
src/vorta/updater.py
src/vorta/utils.py
src/vorta/views/collection_rc.py
src/vorta/views/main_window.py
src/vorta/views/profile_add_edit.py
src/vorta/views/repo_add.py
src/vorta/views/repo_tab.py
src/vorta/views/schedule_tab.py
src/vorta/views/snapshots_tab.py
src/vorta/views/source_tab.py
src/vorta/views/ssh_add.py
tests/conftest.py
tests/test_repo.py
tests/test_snapshots.py

@m3nu see the flake8 ignores in `setup.cfg`, they point to some problematic places in the code.

add flake8 checker, fix trivial issues

---

.travis.yml
setup.cfg
src/vorta/borg/borg_thread.py
src/vorta/borg/create.py
src/vorta/scheduler.py
src/vorta/updater.py
src/vorta/utils.py
src/vorta/views/archive_tab.py
src/vorta/views/collection_rc.py
src/vorta/views/extract_dialog.py
src/vorta/views/main_window.py

also: run flake8 on travis (but only on linux - once is enough).

misc fixes

---

src/vorta/views/archive_tab.py

For mount the behavior is to mount the selected archive if one is
selected and the whole repo when none is selected. The same behavior
was now implemented for check as well.

support checking a single (selected) archive, fixes #33

---

src/vorta/assets/UI/sourcetab.ui
src/vorta/utils.py
src/vorta/views/source_tab.py

it was only possible to add directories. now also single files are addable.

sources: add option to add a single file

---

src/vorta/assets/UI/archivetab.ui
src/vorta/borg/prune.py
src/vorta/models.py
src/vorta/views/archive_tab.py

please review, i am not familiar with qt, qt designer, pewee, etc.

support borg prune --keep-within, fixes #6

---

src/vorta/assets/UI/mainwindow.ui

Remove the maximum size restriction and assign a layout to the main window so it resizes gracefully (but keep the default size to the current one, just don't forbid the user from resizing the window if he/she wants to do it).

Make the main window resizeable

---

.travis.yml
src/vorta/assets/UI/archivetab.ui
src/vorta/borg/delete.py
src/vorta/views/archive_tab.py

My try on fixing https://github.com/borgbase/vorta/issues/119.
I noticed that the size in the archive table makes no sense anymore when you delete one archive.
For example:
- two archives of 500B and 6MB
- 6MB archive gets deleted
- there is only one archive with 500B left which holds data of 6MB

Implement feature to delete specific archive

---

src/vorta/i18n/ts/vorta.de.ts
src/vorta/views/profile_add_edit_dialog.py

"Add Profile" had standard buttons without translations.

Add explicit translation for buttons.

---

setup.cfg
src/vorta/i18n/__init__.py
src/vorta/models.py
src/vorta/views/repo_tab.py

compressor selection: add zlib, add zstd,8, descriptions, fixes #145

---

src/vorta/assets/UI/repoadd.ui
src/vorta/borg/borg_thread.py
src/vorta/borg/info.py
src/vorta/borg/init.py
src/vorta/models.py
src/vorta/views/repo_add_dialog.py
src/vorta/views/repo_tab.py

Added a field to the repo information so additional arguments can be
added to the borg command line. The arguments specified there are
appended to every command that's run on that repo.

Add borg extra arguments (#96)

---

src/vorta/autostart.py

As discussed in https://github.com/borgbase/vorta/issues/126

Fix autostart

---

src/vorta/views/extract_dialog.py

Fix for the line parsing issue mentioned in #215 .

Skip lines that aren't in expected format.

---

Makefile
vorta.spec

Fat binary for all supported platforms

---

Vagrantfile

Improve Vagrantfile to compile on Debian Jessie.

---

src/vorta/application.py
src/vorta/autostart.py
src/vorta/config.py

1) Change socket-file path so that Flatpaks has access
2) Change autostart function so that it detects if it is run as Flatpak

Make Flatpak Ready

---

src/vorta/__main__.py
src/vorta/utils.py

Implement --version

---

Makefile
Vagrantfile

Build macOS version in Vagrant/macOS 10.13 (WIP). Fixes #273

---

src/vorta/__main__.py

Fixes #298.
I mean the optimal case would be if the Adwaita-like style would work, but it is better than nothing.

Force fusion style on Linux

---

src/vorta/assets/UI/repoadd.ui
src/vorta/views/repo_add_dialog.py
tests/test_repo.py

Changes password to borg passphrase

---

src/vorta/__main__.py
src/vorta/qt_single_application.py

Got sometimes "Segmentation Fault" when using foreground option"

Fix "Force-Fusion-Style"

---

src/vorta/views/main_window.py

Refresh archivetable after another profile is selected

Refresh after profile selection

---

Makefile
flatpak/com.borgbase.Vorta.yaml

Include flatpak-install in Makefile

---

src/vorta/views/diff_result.py

Fix a tricky error in borg diff

Fix borg diff

---

src/vorta/views/diff_result.py

Fix diff-bug with removed/added links

---

src/vorta/views/diff_result.py

Fixes the spelling mistake discussed in https://github.com/borgbase/vorta/pull/356

Fix spelling mistake

---

src/vorta/borg/mount.py

Always mount with current user and read-only perms.

---

.travis.yml
CONTRIBUTORS.md
LICENSE.txt
README.md

This is to add a copyright note and list of authors, as suggested in #403.

Add CONTRIBUTORS file and copyright note. Fixes #403

---

src/vorta/views/archive_tab.py
src/vorta/views/diff_dialog.py
src/vorta/views/diff_result.py
src/vorta/views/extract_dialog.py
src/vorta/views/tree_view.py
tests/borg_json_output/diff_archives_stdout.json
tests/conftest.py
tests/test_archives.py
tests/test_repo.py

It now heavily relies on regex.
This was done in order to make the code more stable
and easier to maintain.
Initial testing would be much appreciated as the logic is not trivial and string parsing is error prone. 
I tested it on various combinations with changed permissions, added links, directories and other files, but it is still possible that I missed certain combinations.

Rewrite of borg diff core

---

src/vorta/assets/metadata/com.borgbase.Vorta.desktop

Set StartupWMClass= in com.borgbase.Vorta XDG desktop file

---

src/vorta/utils.py

based on this : [https://leomoon.com/journal/python/high-dpi-scaling-in-pyqt5/](https://leomoon.com/journal/python/high-dpi-scaling-in-pyqt5/)

Correct window size on hidpi screen

---

src/vorta/borg/borg_thread.py

More reliable cancel (WIP)

---

flatpak/com.borgbase.Vorta.json

This PR updates the manifest to the current state on https://github.com/flathub/com.borgbase.Vorta

Update flatpak manifest

---

src/vorta/assets/metadata/com.borgbase.Vorta.desktop

Keywords must not duplicate words in Name nor GenericName.  It might
be useful to add additional Keywords, but I haven't been able to find
a package that duplicates entries from Categories.

Desktop file: fix syntax, enhance Categories, add a Keyword.

---

src/vorta/i18n/ts/vorta.cs.ts
src/vorta/i18n/ts/vorta.de.ts
src/vorta/i18n/ts/vorta.fr.ts
src/vorta/i18n/ts/vorta.it.ts

I've translated the remaining German strings.
Also Pavel Borecki completely translated Czech.

Use newest translation data from transifex

---

src/vorta/assets/UI/sourcetab.ui
src/vorta/views/source_tab.py

Implements request in a different way than suggested, I hope it's still OK
Fixes #466

Add paste button for source paths

---

src/vorta/assets/UI/repotab.ui
src/vorta/views/repo_tab.py

Add copy button for repository URLs/paths

---

.github/workflows/main.yml

Broken test: https://github.com/borgbase/vorta/pull/518/checks?check_run_id=785705990
Fixed test: https://github.com/samuel-w/vorta/pull/1/checks?check_run_id=786333071
This is probably the highest priority issue right now

Update repositories before installing dependencies, fixes broken tests

---

src/vorta/application.py
src/vorta/config.py

Move socket file from state-dir to tmp-dir

---

src/vorta/models.py
src/vorta/views/main_window.py

- stores window width&height in peewee database before closing
- gets the window state during initialization of MainWindow

Save window state

---

.github/workflows/main.yml
setup.cfg
tests/test_source.py

Based on earlier PR by @samuel-w. I removed the earlier `click()` workaround, since it worked everywhere without.

Fix tests for PyQt 5.15 on Linux. By @samuel-w

---

Makefile
package/icon-symbolic.svg
package/icon.svg
src/vorta/notifications.py

Add correct icon for notifications

---

src/vorta/assets/UI/sourcetab.ui
src/vorta/views/source_tab.py

This PR enables as proposed in #593 as number 2.
It's now possible to select & delete multiple entries at once.

Enable multiselection on source list

---

src/vorta/assets/UI/sourcetab.ui
src/vorta/utils.py
src/vorta/views/source_tab.py

Implements number 1 of #593 
I don't think there's a way to add multiple directories, https://doc.qt.io/qt-5/qfiledialog.html#FileMode-enum
Changed wording of the UI:

Add selection of multiple files

---

src/vorta/assets/UI/sourcetab.ui

Number 3 of #593
Change is 3 lines long.

Add autosorting

---

src/vorta/borg/info.py

Fixes #450
Edit: New record! 2 line PR. Wonder if I can ever do a 1 line PR.

Fix adding existing unencrypted repo

---

src/vorta/models.py
src/vorta/views/extract_dialog.py

Months is now exactly accurate.
Closes #185

Use dt.now everywhere, remove unused code

---

src/vorta/views/main_window.py

Fix crash when GUI is opened via tray icon while a backup is running

---

src/vorta/network_status/network_manager.py
tests/network_manager/test_network_manager.py

I've added logging and handled the "partial permissions" situation shown in this comment: https://github.com/borgbase/vorta/issues/629#issuecomment-689077793
This PR contains the commit from #631.

Handle DBusException in NetworkManagerMonitor

---

src/vorta/network_status/abc.py
src/vorta/network_status/network_manager.py

Fixes #669
Arch Linux seems to cause all the problems.

Catch DBusException

---

src/vorta/borg/borg_thread.py

Avoids the performance concerns of https://github.com/borgbase/vorta/pull/615#issuecomment-687600110 by declaring at `borg_thread` init

Translate category labels

---

setup.cfg

Patches https://gitlab.com/pycqa/flake8/-/issues/139, 
since W503 will not be removed https://gitlab.com/pycqa/flake8/-/issues/539

Ignore flake8 W503

---

src/vorta/autostart.py

Removed os library, so it only uses pathlib

Clean up autostart

---

src/vorta/qt_single_application.py

The BSD-2-Clause clearly states what is required for the license to be
valid.
Closes #715

Add valid copyright header to Johan Rade's work

---

src/vorta/borg/create.py

If pre-backup command is set to do some network thing it still runs.
Fixes #699

Limit network checking to only remote repos

---

src/vorta/models.py

Add background settings to all non macos

---

src/vorta/application.py

Ensure user thinks twice before breaking a lock.

Improve break-lock dialog.

---

src/vorta/keyring/kwallet.py

Forgot that non-empty strings cast to True.

Improve kwallet DBus detection

---

src/vorta/__main__.py
src/vorta/application.py
src/vorta/borg/borg_thread.py
src/vorta/views/profile_add_edit_dialog.py

Translations behave weird with inheritance.
The EditProfileWindow requires translation file updates.
#892

Fix translations

---

src/vorta/application.py

This adds a warning to add Vorta as full access application to avoid inaccessible files.
Poll on Twitter: https://twitter.com/borg_base/status/1383302657045979144

Check for full disk access on macOS

---

.github/workflows/test.yml

Inspired by https://news.ycombinator.com/item?id=26825298

Option to run tests with SSH debugging

---

src/vorta/application.py

Called set_progress() on wrong class.

---

src/vorta/views/diff_result.py
src/vorta/views/partials/tree_view.py
tests/test_diff.py

Hello, 
Folders and files are correctly sorted without error and regression :)

Fix for  #1016

---

src/vorta/utils.py

Add new SSH key error

---

src/vorta/log.py
src/vorta/scheduler.py
src/vorta/tray_menu.py
src/vorta/views/main_window.py

Remove jobs before deleting profile

---

src/vorta/views/source_tab.py

Make sure only sources for current profile are removed

---

src/vorta/scheduler.py
src/vorta/views/source_tab.py

Properly save folder stats based on profile

---

MANIFEST.in
setup.cfg
setup.py

Also clean up Manifest and move some settings from setup.py to setup.cfg.

Remove unused setuptools-git dependency

---

src/vorta/network_status/darwin.py

Ignore encoding errors in Wifi names

---

flatpak/dependencies/python3-llfuse.json

See also https://github.com/borgbase/vorta/issues/930#issuecomment-1021717045
@Hofer-Julian

Upgrade llfuse.

---

package/macos-package-app.sh
requirements.d/dev.txt

Adjust for Sparkle 2.0

---

src/vorta/scheduler.py
src/vorta/store/models.py

Change default returncode for log entries to -1.

---

src/vorta/scheduler.py

Fixes #1227.
* src/vorta/scheduler.py (VortaScheduler.set_timer_for_profile): Set timer only if value is smaller than `2**31-1` = 2147483647 else do nothing. Every 15 min vorta will trigger a reschedule.

Fix setting a timer value too large for C++ int.

---

src/vorta/borg/info_repo.py
src/vorta/borg/init.py

Resolves borgbase/vorta#1134

---

src/vorta/views/extract_dialog.py
src/vorta/views/main_window.py
src/vorta/views/profile_add_edit_dialog.py
src/vorta/views/repo_add_dialog.py

* src/vorta/views/extract_dialog.py
* src/vorta/views/main_window.py
* src/vorta/views/profile_add_edit_dialog.py
* src/vorta/views/repo_add_dialog.py

Fix use of `self.tr` for translation.

---

src/vorta/assets/UI/diffdialog.ui
src/vorta/assets/UI/diffresult.ui
src/vorta/assets/UI/extractdialog.ui

Titles changed and translated.
Diff
Diff Results
Extract
Diff
Diff Results
Extract

Resolves #1245 Change Dialog titles to one related to their function

---

src/vorta/views/source_tab.py

This will allow gathering more information about #1080 that was reported two times already but isn't reproducible.

Add some logging to `source_tab.py`.

---

src/vorta/keyring/abc.py
src/vorta/keyring/darwin.py
src/vorta/keyring/db.py
src/vorta/keyring/kwallet.py
src/vorta/keyring/secretstorage.py

They now log storing and retrieving passwords.
* src/vorta/keyring/abc.py (VortaKeyring.get_keyring): Log which keyring has been picked.
* src/vorta/keyring/darwin.py
* src/vorta/keyring/db.py
* src/vorta/keyring/kwallet.py
* src/vorta/keyring/secretstorage.py

Improve logging for keyring functions.

---

src/vorta/assets/UI/archivetab.ui
src/vorta/borg/delete.py
src/vorta/views/archive_tab.py

Allow the user to select multiple lines in the archive view and implement deleting multiple archives.
Fixes #1269.

Select and delete multiple archives.

---

src/vorta/views/repo_tab.py

Remove leftover from changing repo menu

---

src/vorta/views/repo_tab.py

* src/vorta/views/repo_tab.py (RepoTab.copy_URL_action): Remove check of selected index. Construct a proper QMimeData with text and url field.

Fix copying the current repo to the clipboard.

---

src/vorta/scheduler.py

Previously the seconds of the current time or the last backup time were be copied. Fixes #1363.
This also fixes an issue when the scheduled time was missed and the backup is scheduled
for the current day although the time of day set has already passed.
* src/vorta/scheduler.py (VortaScheduler.set_timer_for_profile)

Fix seconds for fixed schedule and fix scheduling for the same day

---

src/vorta/borg/umount.py
src/vorta/views/archive_tab.py

* src/vorta/borg/umount.py (BorgUmountJob.prepare): Add parameters `mount_point` and optional `archive_name`.
Handle them correctly.
* src/vorta/views/archive_tab.py : Remove code that can now be found in `umount.py`.
Translate error messages returned by `BorgUmountJob.prepare`.

Move umount logic from `archive_tab.py` into existing `BorgUmountJob`.

---

README.md

I like badges, do you?
Feel free to add a badge or change their order.

Add badges to `README.md`.

---

src/vorta/borg/mount.py
src/vorta/utils.py
src/vorta/views/archive_tab.py

* src/vorta/views/archive_tab.py : Move all command building logic into `mount.py`.
* src/vorta/borg/mount.py (BorgMountJob.prepare): Add command building logic previously in other places.
* src/vorta/borg/mount.py (BorgMountJob.prepare): Use `-a` command line option to select a single archive.
* src/vorta/utils.py (SHELL_PATTERN_ELEMENT): A pattern that can be used to detect shell pattern syntax.
* src/vorta/utils.py (get_mount_points): Implement parsing a borg v2 cmd.

Specify archive using `-a` for borg v2 `mount`.

---

src/vorta/borg/extract.py

* src/vorta/borg/extract.py (BorgExtractJob.prepare)

Implement v2 compatibility for `borg extract`.

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_form.yaml
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

- enhances the existing bug report template
- adds a feature request template
- links discussions and docs on the issue page
- adds an experimental bug report form
- adds a pull request template
- adds a contributing file

Community enhancement

---

src/vorta/utils.py

* src/vorta/utils.py (get_mount_points)

Migrate to `--match-archives` in mount point detection.

---

src/vorta/borg/_compatibility.py
src/vorta/borg/list_archive.py
src/vorta/borg/prune.py
src/vorta/views/extract_dialog.py

Borg v1.2.2 support

---

src/vorta/borg/borg_job.py
src/vorta/borg/check.py

Show progress on repo check

---

src/vorta/assets/UI/diffresult.ui
src/vorta/assets/UI/extractdialog.ui

* src/vorta/assets/UI/diffresult.ui
* src/vorta/assets/UI/extractdialog.ui

Change label `Folders On Top` to `Folders First` in Extract and Diff view

---

.github/workflows/test.yml

* update actions/setup-python to v4.3.1
* use $GITHUB_OUTPUT instead of `::set-output`

Update usage of deprecated features in test.yml.

---

.github/ISSUE_TEMPLATE/bug_form.yaml

Fix small typo in bug template

Fix typo in issue bug template

---

src/vorta/assets/UI/repoadd.ui
src/vorta/borg/_compatibility.py
src/vorta/borg/borg_job.py
src/vorta/borg/check.py
src/vorta/borg/compact.py
src/vorta/borg/create.py
src/vorta/borg/delete.py
src/vorta/borg/diff.py
src/vorta/borg/extract.py
src/vorta/borg/info_archive.py
src/vorta/borg/info_repo.py
src/vorta/borg/init.py
src/vorta/borg/list_archive.py
src/vorta/borg/list_repo.py
src/vorta/borg/mount.py
src/vorta/borg/prune.py
src/vorta/borg/rename.py
src/vorta/borg/umount.py
src/vorta/tray_menu.py
src/vorta/utils.py
src/vorta/views/archive_tab.py
src/vorta/views/repo_add_dialog.py

Support for breaking changes in Borg v2

---

pyproject.toml
requirements.d/dev.txt

As per https://github.com/borgbase/vorta/pull/1578#issuecomment-1416799997

Specify build system

---

src/vorta/borg/prune.py

I think the issue #1564 is fixed just by changing the version check. I tested it locally and archives are getting pruned as intended.

Fix issue 1564

---

.github/pull_request_template.md
.gitignore
requirements.d/dev.txt

for borgbase/vorta.borgbase.com#32

Add `pre-commit` to developer requirements.

---

README.md

That's enough, @real-yfprojects ?
Preview: https://github.com/m3nu/vorta/tree/minor/gsoc-intro

Add GSoC link

---

src/vorta/utils.py

Fixes issue where negative difference in size of two archive raises math error
Fixes #1650 
Manually by trying different scenarios

Fixes math error for negative size in diff view in archive tab

---

tests/unit/test_import_export.py

This test module covered most of `ImportWindow` methods, and the tests did not need much cleanup or parametrization. 
I only added one new test, `test_import_exceptions`, which ensures the correct error message is displayed when an exception occurs during profile import. I parametrized it to cover four different possible exceptions.
#1754 
One of my Google Summer of Code projects involves cleaning up the Vorta tests, reducing duplicated code, and increasing code coverage.
This test has passed my local testing as well as GitHub CI checks.

PR: `tests/unit/test_import_export`: increased test coverage

---

requirements.d/dev.txt
src/vorta/assets/UI/repoadd.ui
src/vorta/views/repo_add_dialog.py

#issue1807
thought it would be a better to give these windows better titles
####New repo window:
####Existing repo window:
- [x ] I have read the [CONTRIBUTING](https://vorta.borgbase.com/contributing/) guide.
- [ x] My code follows the code style of this project.

Changed title of adding `new repo` and `existing repo` windows to be more user-friendly and informative

---

README.md

Update screencast for v0.9

---

src/vorta/assets/exclusion_presets/dev.json

Added exclusion patterns for VSCode cache and config files, Android Studio artefacts, and npm-global
Was mentioned in a conversation about Exclude-GUI.
Tested manually by me.

VSC and android exclusion patterns

---

src/vorta/assets/exclusion_presets/dev.json

delete duplicate entry of flatpak builder cache

---

src/vorta/application.py

Catch case of none-existant profile from logs

---

src/vorta/borg/_compatibility.py
src/vorta/borg/borg_job.py
src/vorta/borg/create.py
src/vorta/borg/info_repo.py
src/vorta/borg/init.py
src/vorta/borg/list_repo.py

- new repo-* commands (previously: r*)
- some stats are gone
I did some manual testing with a local fs repository.

borg2: support >= b10, drop support for < b10

---

.github/actions/install-dependencies/action.yml
.github/workflows/build-macos.yml
.github/workflows/test.yml
src/vorta/assets/metadata/com.borgbase.Vorta.appdata.xml

Build and packaging fixes

---

src/vorta/i18n/__init__.py

Workaround to load right language

---

src/vorta/views/main_window.py
src/vorta/views/shell_commands_page.py

Ensure pre/post-backup cmds are populated

---

src/vorta/views/main_window.py

Update network settings on profile change

---

setup.cfg

It hasn't been needed since 0e8432602d92aa015ae100044b5c196e32ccf87b.

remove setuptools from install_requires

---

.github/workflows/build-macos.yml
.github/workflows/test.yml
src/vorta/assets/metadata/com.borgbase.Vorta.appdata.xml

This PR is intended to fix the broken transifex link

Fix broken transifex link
